package com.mycompany.hibernatetemplate3.entities;
// Generated Apr 23, 2017 9:08:16 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * ContactsInfo generated by hbm2java
 */
public class ContactsInfo  implements java.io.Serializable {


     private Integer id;
     private String name;
     private String email;
     private String mobileNumber;
     private Set users = new HashSet(0);

    public ContactsInfo() {
    }

	
    public ContactsInfo(String name, String email, String mobileNumber) {
        this.name = name;
        this.email = email;
        this.mobileNumber = mobileNumber;
    }
    public ContactsInfo(String name, String email, String mobileNumber, Set users) {
       this.name = name;
       this.email = email;
       this.mobileNumber = mobileNumber;
       this.users = users;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getMobileNumber() {
        return this.mobileNumber;
    }
    
    public void setMobileNumber(String mobileNumber) {
        this.mobileNumber = mobileNumber;
    }
    public Set getUsers() {
        return this.users;
    }
    
    public void setUsers(Set users) {
        this.users = users;
    }




}


