package com.mycompany.hibernatetemplate2.entities;
// Generated Apr 22, 2017 3:48:49 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private Integer userId;
     private String username;
     private String userpass;
     private String userEmail;
     private String userPhone;
     private Set contactsInfos = new HashSet(0);

    public User() {
    }

    public User(Integer userId) {
        this.userId = userId;
    }

    @Override
    public String toString() {
        return "User{" + "userId=" + userId + ", username=" + username + ", userpass=" + userpass + ", userEmail=" + userEmail + ", userPhone=" + userPhone + ", contactsInfos=" + contactsInfos + '}';
    }

	
    public User(String username, String userpass, String userEmail, String userPhone) {
        this.username = username;
        this.userpass = userpass;
        this.userEmail = userEmail;
        this.userPhone = userPhone;
    }
    public User(String username, String userpass, String userEmail, String userPhone, Set contactsInfos) {
       this.username = username;
       this.userpass = userpass;
       this.userEmail = userEmail;
       this.userPhone = userPhone;
       this.contactsInfos = contactsInfos;
    }
   
    public Integer getUserId() {
        return this.userId;
    }
    
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getUserpass() {
        return this.userpass;
    }
    
    public void setUserpass(String userpass) {
        this.userpass = userpass;
    }
    public String getUserEmail() {
        return this.userEmail;
    }
    
    public void setUserEmail(String userEmail) {
        this.userEmail = userEmail;
    }
    public String getUserPhone() {
        return this.userPhone;
    }
    
    public void setUserPhone(String userPhone) {
        this.userPhone = userPhone;
    }
    public Set getContactsInfos() {
        return this.contactsInfos;
    }
    
    public void setContactsInfos(Set contactsInfos) {
        this.contactsInfos = contactsInfos;
    }




}


